/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about'
    }
  },
  {
    name: 'gateway',
    path: '/gateway',
    component: 'layout.base',
    meta: {
      title: 'gateway',
      i18nKey: 'route.gateway'
    },
    children: [
      {
        name: 'gateway_cache',
        path: '/gateway/cache',
        component: 'view.gateway_cache',
        meta: {
          title: 'gateway_cache',
          i18nKey: 'route.gateway_cache'
        }
      },
      {
        name: 'gateway_routing-config',
        path: '/gateway/routing-config',
        component: 'view.gateway_routing-config',
        meta: {
          title: 'gateway_routing-config',
          i18nKey: 'route.gateway_routing-config'
        }
      },
      {
        name: 'gateway_whitelist-recommend',
        path: '/gateway/whitelist-recommend',
        component: 'view.gateway_whitelist-recommend',
        meta: {
          title: 'gateway_whitelist-recommend',
          i18nKey: 'route.gateway_whitelist-recommend'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'home-drilldown',
    path: '/home/drilldown',
    component: 'layout.base$view.home-drilldown',
    meta: {
      title: 'home-drilldown',
      i18nKey: 'route.home-drilldown'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'llm',
    path: '/llm',
    component: 'layout.base',
    meta: {
      title: 'llm',
      i18nKey: 'route.llm'
    },
    children: [
      {
        name: 'llm_api-key',
        path: '/llm/api-key',
        component: 'view.llm_api-key',
        meta: {
          title: 'llm_api-key',
          i18nKey: 'route.llm_api-key'
        }
      },
      {
        name: 'llm_app-client',
        path: '/llm/app-client',
        component: 'view.llm_app-client',
        meta: {
          title: 'llm_app-client',
          i18nKey: 'route.llm_app-client'
        }
      },
      {
        name: 'llm_model',
        path: '/llm/model',
        component: 'view.llm_model',
        meta: {
          title: 'llm_model',
          i18nKey: 'route.llm_model'
        }
      },
      {
        name: 'llm_project',
        path: '/llm/project',
        component: 'view.llm_project',
        meta: {
          title: 'llm_project',
          i18nKey: 'route.llm_project'
        }
      },
      {
        name: 'llm_provider',
        path: '/llm/provider',
        component: 'view.llm_provider',
        meta: {
          title: 'llm_provider',
          i18nKey: 'route.llm_provider'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_logininfor',
        path: '/monitor/logininfor',
        component: 'view.monitor_logininfor',
        meta: {
          title: 'monitor_logininfor',
          i18nKey: 'route.monitor_logininfor'
        }
      },
      {
        name: 'monitor_online',
        path: '/monitor/online',
        component: 'view.monitor_online',
        meta: {
          title: 'monitor_online',
          i18nKey: 'route.monitor_online'
        }
      },
      {
        name: 'monitor_operlog',
        path: '/monitor/operlog',
        component: 'view.monitor_operlog',
        meta: {
          title: 'monitor_operlog',
          i18nKey: 'route.monitor_operlog'
        }
      }
    ]
  },
  {
    name: 'social-callback',
    path: '/social-callback',
    component: 'layout.base$view.social-callback',
    meta: {
      title: 'social-callback',
      i18nKey: 'route.social-callback'
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_client',
        path: '/system/client',
        component: 'view.system_client',
        meta: {
          title: 'system_client',
          i18nKey: 'route.system_client'
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_notice',
        path: '/system/notice',
        component: 'view.system_notice',
        meta: {
          title: 'system_notice',
          i18nKey: 'route.system_notice'
        }
      },
      {
        name: 'system_oss',
        path: '/system/oss',
        component: 'view.system_oss',
        meta: {
          title: 'system_oss',
          i18nKey: 'route.system_oss'
        }
      },
      {
        name: 'system_oss-config',
        path: '/system/oss-config',
        component: 'view.system_oss-config',
        meta: {
          title: 'system_oss-config',
          i18nKey: 'route.system_oss-config'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_tenant',
        path: '/system/tenant',
        component: 'view.system_tenant',
        meta: {
          title: 'system_tenant',
          i18nKey: 'route.system_tenant'
        }
      },
      {
        name: 'system_tenant-package',
        path: '/system/tenant-package',
        component: 'view.system_tenant-package',
        meta: {
          title: 'system_tenant-package',
          i18nKey: 'route.system_tenant-package'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center'
    }
  }
];
